### ISSUE TITLE
Widget assocition-rules does not appear, Orange 3.7

### ISSUE THREAD

**Issue by ajsp** [biolab/orange3-associate#15]
##### Associate version

Version 3.7
gir revision: e730793

##### Expected behavior
I use orange3 associates in my masters work. in the orange3 3.7 version, the association rules widget does not appear. Thank you.

##### Actual behavior
The association rules widget does not appear.

##### Steps to reproduce the behavior
Install widget from Orange3.

**Comment by ajdapretnar** [comment]
Could you please run Orange from the terminal with
`python -m Orange.canvas -l 4`
Thanks!

**Comment by ajsp** [comment]
Does not work. Widget association does not appear.

**Comment by ajsp** [comment]
(Orange) C:\WINDOWS\system32>python -m Orange.canvas -l 4
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x07A98940>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Loading widget registry cache ('C:\\Users\\Antonio\\AppData\\Roaming\\Orange\\3.7.0\\Cache\\canvas\\registry-cache.pck').
Ignoring 'C:\\Program Files (x86)\\Orange\\lib\\site-packages\\Orange\\widgets\\data\\contexthandlers.py'.
Could not import 'Orange.widgets.visualize.owparallelcoordinates'.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\widgets\visualize\owparallelcoordinates.py", line 14, in <module>
    from Orange.widgets.visualize.owparallelgraph import OWParallelGraph
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\widgets\visualize\owparallelgraph.py", line 17, in <module>
    from Orange.widgets.utils.plot import OWPlot, UserAxis, AxisStart, AxisEnd, OWCurve, OWPoint, PolygonCurve, \
ImportError: cannot import name 'OWPlot'
Could not import 'Orange.widgets.visualize.owparallelgraph'.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\widgets\visualize\owparallelgraph.py", line 17, in <module>
    from Orange.widgets.utils.plot import OWPlot, UserAxis, AxisStart, AxisEnd, OWCurve, OWPoint, PolygonCurve, \
ImportError: cannot import name 'OWPlot'
Ignoring 'C:\\Program Files (x86)\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owscatterplotgraph.py'.
Ignoring 'C:\\Program Files (x86)\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owtreeviewer2d.py'.
Ignoring 'C:\\Program Files (x86)\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\owviswidget.py'.
Ignoring 'C:\\Program Files (x86)\\Orange\\lib\\site-packages\\Orange\\widgets\\visualize\\pythagorastreeviewer.py'.
Ignoring 'C:\\Program Files (x86)\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\contexthandlers.py'.
Ignoring 'C:\\Program Files (x86)\\Orange\\lib\\site-packages\\Orange\\widgets\\evaluate\\utils.py'.
Error while importing 'orangecontrib.associate.widgets.owassociate'.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "C:\Program Files (x86)\Orange\lib\site-packages\Orange\canvas\registry\discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Program Files (x86)\Orange\lib\site-packages\orangecontrib\associate\widgets\owassociate.py", line 252
    super().__init__(*args, **kwargs, sortRole=OWAssociate.ITEM_DATA_ROLE)
                                    ^
SyntaxError: invalid syntax
Saving widget registry cache with 84 entries ('C:\\Users\\Antonio\\AppData\\Roaming\\Orange\\3.7.0\\Cache\\canvas\\registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x07BB8A80> on 'CanvasScene(objectName='', ...)'.
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3 3.7.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3-Associate 1.1.4

**Comment by kernc** [comment]
@markotoplak, is `some_func(*args, **kwargs, some_kw=4)` invalid syntax in Python 3.4?

**Comment by ajsp** [comment]
How can I fix it?

**Comment by kernc** [comment]
Use the Miniconda installer: https://orange.biolab.si/download/files/Orange3-3.7.0-Miniconda-x86_64.exe

**Comment by ajsp** [comment]
Forever? Or I have a problem with the installation?

**Comment by kernc** [comment]
Yes, until the add-on gets fixed (should be in the next couple of days), you can use the [Miniconda installer](https://orange.biolab.si/download/windows), which should work fine, with the add-on installing just fine.

**Comment by ajsp** [comment]
Ok. Thank you.

**Comment by astaric** [comment]
@kernc, has this been fixed yet? We have encountered this error at the workshop today as well.
